### ISSUE TITLE
Disable specific network adapters

### ISSUE THREAD

**Issue by addrum** [ArcadeRenegade/SidebarDiagnostics#16]
I have a long list of network adapters with some I don't use often (Virtual Machines, LogMeIn Hamachi etc) so it would be nice to display a list under the Network monitor option (drop down -> list of network adapters with checkboxes maybe?) so I can pick and choose which to display.

![image](https://cloud.githubusercontent.com/assets/2855069/12688142/2bf02f08-c6cc-11e5-98a6-e1e0d10d5314.png)

**Comment by ArcadeRenegade** [comment]
Sounds good.

**Comment by ksarnelli** [comment]
I'd like this feature as well.  Also, there appears to be a bug (visible in addrum's screenshot) in which each VMWare Virtual Ethernet Adapter is displayed twice.

**Comment by ArcadeRenegade** [comment]
It is already implemented and ready for the next release. I'm just trying to clean up the UI for it and add one more enhancement before the release. 

The bugs with multiple network interfaces is because I am trying to get only the active nics and the names are very slightly different between performance counters and the network interface  .NET library. So in order to match them I have to create a canonical name for them by removing non alphabetical characters in their name string. 

This leads to unintended behavior with nics that have the same name as you can see here. 

With the implementation of letting the user disable whatever hardware they want, I will remove this automatic check for active nics and let the user handle disabling the unnecessary or inactive nics they don't want shown. 

Thanks.

**Comment by ksarnelli** [comment]
Great, thanks!

**Comment by ArcadeRenegade** [comment]
Implemented
