### ISSUE TITLE
No Core Tempurature With Ryzen 1600

### ISSUE THREAD

**Issue by cj360** [ArcadeRenegade/SidebarDiagnostics#171]
Running:
**1. Windows 10 Creators Update
**2. Latest release 3.4.5
**3. Core temp is selecting in sidebar's settings but it's not displayed.
**4. Setting the cpu temp on, no value is displayed.
[picture](http://i.imgur.com/fAaFD97.png)

**Comment by NoRoboto** [comment]
I have the same issue on my Ryzen 1700. 
Running:
**1. Windows 10 Creators Update
**2. Latest release 3.4.5

**Comment by JanneSaukkio** [comment]
Same issue here with
- Ryzen 5 1500X
- Windows 7 SP1
- Latest release 3.4.5

CPU is showing as two (should be one with 4c/8t) and temperatures or clock speeds aren't showing

[Picture](http://i.imgur.com/HnInmLR.png)

**Comment by IISlapDashII** [comment]
I'd hazard a guess & say the reason for this is due to Open Hardware Monitor not yet including support for Family 17th (Zen) AMD CPU's yet. 

The last update for OHM was Version 0.8.0 Beta & it included the following:

- Added support for Intel Skylake, Kaby Lake and Airmont CPUs.
- Added support for Intel Xeon E5-26xx v4 and Xeon D-15xx CPUs.
- Added support for Intel Intel i5, i7 5xxC (14nm) CPUs.
- Added support for AMD family 15h model 30h APUs.
- Added support for ITE IT8620E and IT8628E super I/O chips.
- Added support for Nuvoton NCT6102D/NCT6106D super I/O chips.
- Added more Nvidia RAM sensors (free, used and total).
- Added more sensors for Samsung and Plextor SSDs.
- Replaced the ‘Temperature Difference From 100’ with a simple ‘Temperature’ sensor on hard drives.
- Fixed wrong Nvidia GPU clock min and plotting values.
- Fixed issues with Nuvoton NCT6791D super I/O chips after wake from S3 sleep state.
- Fixed incorrect OS version showing up in reports for Windows 10 and 8.1.
- Added customizable pen colors for the plot window.
- Improved the automatic plot pen color assignment strategy

ArcadeRenegade will hopefully & most likely update Sidebar Diagnostics once a new release is available to use.

**Comment by ArcadeRenegade** [comment]
Closing this as Ryzen should be supported with LibraHardwareMonitor. People are reporting an issue with CPU temps being too high but I have a fix for that soon.
