### ISSUE TITLE
Slightly increased CPU usage since 2.41

### ISSUE THREAD

**Issue by tubikcz** [ArcadeRenegade/SidebarDiagnostics#32]
I noticed that since version 2.41 the CPU usage on my i5 is always between 2-3%, however with older versions it was usually between 0-0,4%.

Probably not a big deal on good CPUs, but can have impact on weaker systems.

**Comment by ArcadeRenegade** [comment]
I don't think there was anything implemented that would impact cpu usage over time. There are a lot of variables to consider here. But nothing specific to the sidebar.

**Comment by ArcadeRenegade** [comment]
I'll leave this open for other users to report cpu usage issues.

**Comment by BarrowsKing** [comment]
Same here, I installed the 3.0 version and instantly removed it and went back to 2.2. I play oldschool RuneScape (yes, some still play) which is running in Java and can be very sensitive when it comes to running perfectly smooth. No issues with 2.2 but with 3.0, it made the game choppy. I get the same choppiness when I have a steam notification or watching twitch on my secondary monitor and well, I have the Sidebar running on the secondary monitor. 

A few things affect me in this way so don't take this too seriously, just wanted to mention it.

**Comment by Idearum** [comment]
I dunno... It seems to hover around 1-2% all the time for me, which is a bit weird since it is constantly above Skype, Chrome AND an active virtualized Windows 7 in VMware Workstation in terms of CPU usage.

Recording: https://dl.dropboxusercontent.com/u/2161168/ShareX/2016/02/2016-02-16_12-15-47.mp4

I personally don't notice it (probably because this laptop has 8 threads) but I can see how the behaviour can be argued to be slightly on the upper side, for what it does. 

FYI: In the recording Task Manager is set to Update Speed: High, meaning it updates every half-second instead of only once. That's why it looks sped up.

**Comment by Idearum** [comment]
Okay, there's definitely something weird going on.

Recording: https://dl.dropboxusercontent.com/u/2161168/ShareX/2016/02/2016-02-16_12-31-59.mp4

That recording was taken with all monitors and the clock disabled. Basically the only thing the application does is show a transparent black image on screen: http://i.imgur.com/J0WzIMO.png

I really fail to see how a static transparent image warrants that CPU usage (unless the clock and monitors are always active in the background, even when disabled).

**Comment by ArcadeRenegade** [comment]
Even if you disable all monitors the computer object is still opened from
OpenMonitorHardwareLib.dll. Which is probably what that CPU usage is. On
top of that there is also events for the appbar and such.

**Comment by ArcadeRenegade** [comment]
It may have gone down in 3.0.5. I removed code that updated each hardware's subhardware as it wasn't necessary.

**Comment by ArcadeRenegade** [comment]
Hey @tubikcz

You were absolutely correct. There were two issues causing high CPU that were implemented in version 2.4.1 both related to the loading widget.

@campbeb helped me figure it out in #50 

They are fixed in the new version v3.0.7.
