### ISSUE TITLE
GPU Numbering

### ISSUE THREAD

**Issue by shotgun** [ArcadeRenegade/SidebarDiagnostics#65]
Love the Sidebar!  Does Everything I personally need Except...
GPU Numbering/Indexing.
SLI cards are not in order the best I can tell, my 2 cards show reversed in the order they are mounted to the motherboard. Top card seems to be listed second observing card temps. I un-plugged my bottom card seeking some verification but this only served to remove the card from the Sidebar. I was hoping the motherboard still recognized it, no such luck.
It's a small thing I know and I don't even know the trouble it would be to amend. Keep up the great work!
Regards.

**Comment by campbeb** [comment]
For reference, this number can be found in the Identifier.

![clipboard01](https://cloud.githubusercontent.com/assets/1089399/13549934/804af2ca-e2df-11e5-814f-cdeed4c726ca.png)

**Comment by shotgun** [comment]
Could you help an old Granpa out? The above screenshot of code (dude,waay out of my reach) is showing the hardware as discovered by your program right?
I need to flip My discovered cards order as listed in the program? -oh boy-
I'm up for a challenge just need the reins pulled in the right direction.
Thnx for your time.

**Comment by ArcadeRenegade** [comment]
I think @campbeb was just trying to help me out.

@shotgun 

So do you just need to change the order that the cards appear in the sidebar? 

Or are you saying the first card shown in the sidebar is displaying the data for your second? card?

**Comment by shotgun** [comment]
Yes, I'd like to verify the order/index that the cards appear on the sidebar.
As is, it's a guess.

**Comment by shotgun** [comment]
Clarification:
I'd like to see the card slotted in the #1 motherboard PCie slot designated as #1 and so on.
I'm convinced by my card temps I'm seeing the reverse.
Top card typically runs hotter in SLI. It's a small thing but I'm weird thatway.

**Comment by shotgun** [comment]
I have C:,D:,and E: Drives discovered and listed on my Sidebar. Something similar but Numeric for the GPU's.

**Comment by ArcadeRenegade** [comment]
The default order is determined by the Open Hardware Monitor library. I do not know what their order is based off of. I'm assuming it is PCI slot number. I have two Nvidia cards in SLI and mine are displayed in the correct order (top PCI slot first, bottom PCI slot second). I can tell this because GPU # 1 in the sidebar has it's core load increasing when I play games that do not support SLI but the second does not.

If you want to confirm the GPU index open this file:

%localappdata%/SidebarDiagnostics/settings.json

Scroll down to the "MonitorConfig" record where "Type" is equal to 2.
There are records of your GPUs there under "Hardware".
Check the number at the end of their "ID",
This is the index given to the GPU by Open Hardware Monitor.

If you want to confirm, then please download Open Hardware Monitor from their website.
http://openhardwaremonitor.org/

There is also an "Order" property.
The GPU with a higher "Order" number shows up first in the sidebar.

![image](https://cloud.githubusercontent.com/assets/13874898/13550788/658ee3d8-e2da-11e5-8370-94332ab55bb8.png)


If you want to just change the order that they appear in the sidebar, you can open the sidebar settings, go to the monitors tab, click on GPU, and drag the hardware rows to whatever order you want.

![image](https://cloud.githubusercontent.com/assets/13874898/13550795/815b5812-e2da-11e5-8145-ce79a9c250f0.png)

**Comment by shotgun** [comment]
Ha, Much Thanks. And I am running EVGA GTX970's,lol
I'll get to it and leave you be.

**Comment by ArcadeRenegade** [comment]
I'm running the same. Seems to be ok.

![image](https://cloud.githubusercontent.com/assets/13874898/13550833/758429e6-e2db-11e5-9d93-1c481f4a87e9.png)

**Comment by shotgun** [comment]
Dang, I'm all stock FTW+ with the AC whatevers, haven't jumped to the OC on video yet.
All new game to me, quit hotrods/boats/motorcycles. New outlet.
![20160211_171858 - copy - copy](https://cloud.githubusercontent.com/assets/17675955/13550879/56fdb12e-e2ed-11e5-868c-8e9c17babd9d.jpeg)

**Comment by shotgun** [comment]
Been using Dell boxes and laptops since '95,decided to up my game.
(-:

**Comment by ArcadeRenegade** [comment]
haha nice. overclocking the video card isn't hard just time consuming to get the settings right. be sure to download EVGA Precision X when you get started.

**Comment by shotgun** [comment]
Yah, I have it, use it for fans, haven't jumped the rope yet on the OC part. I'm running a 4K monitor also so that's next on the "to do list", I play Planetside2/Hawken/ESO no issues stock but Fallout4 and Witcher3 seem to need more beans.
Anyway, Thanks Again for your work. I used to run RainMeter for my info. No more.
Cheers.

**Comment by shotgun** [comment]
Just an update, click and drag to order and discovered ability to add my own numeric.
Thnx.
