### ISSUE TITLE
Problem by reinstalling 

### ISSUE THREAD

**Issue by Girtablulu** [ArcadeRenegade/SidebarDiagnostics#66]
If you uninstall the sidebar and try to reinstall it again, you will get an error because under %user/Appdata/local is still the Sidebar file, you have to restart your PC (because it says the files are still in use) and than delete the file. 

After you done this you can install the app.

**Comment by ArcadeRenegade** [comment]
The library I use for monitoring CPU, RAM, and GPU is Open Hardware Monitor. It uses winring0 and this creates a .sys file. Sometimes this file is not destroyed when I close the OHM library and it still has the exclusive file lock on it. This is probably what is causing the issue. Unfortunately I do not have a fix for it. But the issue is fairly uncommon at least.

**Comment by Girtablulu** [comment]
yea of course this situation will hardly happen but I thought better report it you never know

**Comment by ArcadeRenegade** [comment]
It's OK, I'd prefer that stuff like this is reported. I'm just explaining the situation in case you or anyone else is curious. I'll leave this open.

**Comment by ArcadeRenegade** [comment]
added to the Wiki instead.
