### ISSUE TITLE
[Feature Request] Battery Percent for Laptops

### ISSUE THREAD

**Issue by PixPMusic** [ArcadeRenegade/SidebarDiagnostics#70]
Might look into adding this myself, but it would be great if we had a battery percent meter on the sidebar. Maybe even power draw or something would be cool.

**Comment by KawaiiPotato** [comment]
Sidebar Diag is meant to display statistics and usage data on system components not directly exposed by the OS. Battery % is already exposed in the taskbar.

**Comment by iPonyRadio** [comment]
Fair. It has just been mentioned by multiple users, and the actual
percentage and voltage/amperage draw (if possible) isn't exposed in the
taskbar directly

**Comment by ArcadeRenegade** [comment]
I think it would be OK as long as it is disabled by default since most users have a desktop. 

I would only be able to get battery percentage though. Amperage and wattage would be impossible I think.

**Comment by iPonyRadio** [comment]
I wasn't aware if Windows had the API. I know some versions of the Linux
kernel and Android have them exposed.

**Comment by cpm10682** [comment]
Not a bad option to add for those that want it. Similar to what HWMonitor shows...

**Comment by iPonyRadio** [comment]
Mind, it might be calculated and theoretical

Still, having the voyage, frequency and wattage would be ice.

Mind, I don’t believe the wattage estimate includes other peripherals. Only the CPU.

**Comment by iPonyRadio** [comment]
Interestingly enough, Intel’s utility for monitoring your system performance, the Power Gadget, will display temps, frequencies, and WATTAGE, so the API is …somewhere...On Apr 28, 2016, at 11:53 AM, cpm10682 <notifications@github.com> wrote:Not a bad option to add for those that want it. Similar to what HWMonitor shows...—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by santiagosony** [comment]
Please, also add the wear/ageing of the battery as data, also cycles counts. This info is not directly available to the user.

Thanks.
