### ISSUE TITLE
[Feature Request] Add a few more monitoring options

### ISSUE THREAD

**Issue by ghost** [ArcadeRenegade/SidebarDiagnostics#82]
I love your monitor!! It has almost replaced open hardware monitor and HWMonitor for me. The only things that open hardware monitor has, that I haven't seen in the sidebar are: temp monitoring for hard drives and GPU shader speed. HWMonitor includes individual battery cell details and also has a built in tracker for min and max detected temperatures. If you are able to add these features to yours, you will blow every other monitor out of the water. Excellent work!!

**Comment by ArcadeRenegade** [comment]
The monitoring in sidebar diagnostics is handled using Performance Counters instead of using Open Hardware Monitor. The reason for that is OHM monitors the drive hardware, whereas SD monitors the logical drives. The reason for that is OHM does not have the drive letter that the drive is assigned to in Windows, which is how most people identify their drives. So drive temperatures are not available.

HWMonitor is developed by CPUID and they have their own very powerful system monitoring SDK. Their SDK is not open source and is targeted to enterprise licensing. So a lot of the data they have I just can't get easily.
